#!/usr/bin/env bash
function alias_if_exists() {
  # Does the alias only if the aliased program is installed
    if command -v $2 > /dev/null; then
        alias "$1"="$2"
    fi
}


# Better defaults
alias crontab="VIM_CRONTAB=true crontab"
alias_if_exists 'diff' 'colordiff'
alias_if_exists 'vim' 'nvim'
alias_if_exists 'v' 'nvim'


# Shortcuts

mvr () {
    # reverse mv
    mv $2 $1
}

## Git
alias ga='git add'
alias gs='git status'
#alias gcm='git commit'
#alias gck='git checkout'
alias gu='git pull'
alias gg='git graph'
# unalias gd
alias gd='git diff'
alias gsu='git stash && git pull && git stash pop'
  # Note that gs is also ghostscript
alias ghostscript="/usr/local/bin/gs"
function gD(){
    git diff $@ | ydiff
}

## Jupyter
alias jc="jupyter console"
alias jco="jupyter nbconvert"
alias jn="jupyter notebook"
alias jn-b="jupyter notebook --no-browser"

## Misc
alias my-ip="curl ipinfo.io/ip 2> /dev/null"
alias spell='aspell check --dont-backup'
alias grepc="grep -P --color=always" #Color grep

alias printpath='echo $PATH | sed "s/:/\\n/g"'
# Other
alias sep='tput cols | python -c "import sys; print(\"=\"*int(sys.stdin.read().strip()))"'

alias tn='tmux new -s '
alias ta='tmux a -t '
alias td='tmux detach'

###########################################################################################################################




# OS dependent aliases
case "$(uname -s)" in

   Darwin)
     # 'Mac OS X'

     alias clear-dnscache="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
     alias bu="brew update && brew outdated | xargs brew upgrade  && brew cleanup -s --prune=0"

     alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome &"

     alias readlink="greadlink"

     alias mvf='mv "$(pfs)"' # Move current finder selection

     # MacOS GNUs
     for i in awk cat chgrp chmod chown chroot cut date df du echo egrep env false fgrep find grep join kill link ln logname make mkdir mknod mktemp mv nice nohup paste perf printf pwd readlink realpath rm rmdir sed sort split tac tail tar tee test touch tr true truncate tty uniq unlink unzip uptime users who whoami yes zip; do
       alias_if_exists "$i" "g$i"
     done
     alias_if_exists "id" "/usr/local/bin/gid"
     alias rm="/usr/local/bin/grm -i"
     alias mv="/usr/local/bin/gmv -i"
     alias cp="/usr/local/bin/gcp -i"
     alias_if_exists "ls" "/usr/local/bin/gls"
     ;;

   Linux)
     # echo 'Linux'
     ;;

   CYGWIN*|MINGW32*|MSYS*)
     # echo 'MS Windows'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     # echo 'other OS'
     ;;
esac


# Shell dependent Alias (only zsh has global aliases)
case $SHELL in
*/zsh)
   # assume Zsh
   ;;
*/bash)
   # assume Bash
   ;;
*)
   # assume something else
   ;;
esac
